diff_controller:
  ros__parameters:
    wheel_separation: 0.17 # measure yours
    wheel_radius: 0.03
    max_wheel_speed: 0.7 # m/s at full pulse - we tune later

    lf_pin: 27
    lb_pin: 21
    rf_pin: 17
    rb_pin: 20

    lf_stop: 1550 # <-- YOUR table here
    lb_stop: 1490
    rf_stop: 1480
    rb_stop: 1480

    left_reversed: false # flip this if left side went backward
    right_reversed: true
    pwm_range: 400 # 400 = 1100 to 1900us. Use 500 if yours needs more power
